sudo: false

# CMake 2.8.9 is needed to build libswiftnav, but Travis only supports
# an earlier version. This sets up that dependency. See also:
#   https://gist.github.com/winterz/10cc2741d466cbd8ff21
#   https://github.com/travis-ci/travis-ci/issues/2030

cache: pip

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake
    - check
    - lcov

before_install:
  - gem install coveralls-lcov
  - pip install --user tox
  # Hack so python bindings can find locally installed library file
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/build/install/usr/local/lib

script:
  # Test libswiftnav
  - mkdir build
  - cd build/
  - cmake -DCMAKE_BUILD_TYPE=Coverage ../
  - make
  # Install locally to avoid sudo
  - make DESTDIR="./install" install
  - ls $LD_LIBRARY_PATH
  # Test libswiftnav-python
  - cd ../python
  - tox

after_success:
  - cd $TRAVIS_BUILD_DIR
  - lcov --compat-libtool --directory . --capture --output-file coverage.info
  # Remove coverage info for tests (always 100%) and stdlib
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - coveralls-lcov coverage.info
